baseURL = "https://marcoaguilera.dev/"
locale = "en-us"
title = "Marco Aguilera"
theme = "PaperMod"

[pagination]
pagerSize = 10

[params]
defaultTheme = "dark"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
mainSections = ["projects", "posts"]
ShowHome = true

description = "Site Reliability Engineer | Observability | Platform Engineering | AI Infrastructure"

[params.profileMode]
enabled = true
title = "Hello, I'm Marco Aguilera"
subtitle = """I'm a Site Reliability Engineer specializing in Observability, Platform Engineering, and AI Infrastructure.

Over the last few years I have worked at a Global Enterprise Company that sells amazing chips and drinks at a local
store near you. My focus has been leading the Observability Stack and managing thousands of datastreams with the best 
industry practices to provide end to end visibility.

I enjoy understanding how technology works, so I will be using this space to write about my projects, and experiences
with Enterprise Engineering and everything else under the sun."""


[menu]

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 10

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts/"
weight = 20


